"""
Django settings for chronoverify project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
from celery.schedules import crontab
from corsheaders.defaults import default_headers
import firebase_admin
from firebase_admin import credentials
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
)

# Read .env file
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-morshed-nayeem-secret-key"
)

DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default="localhost").split(",")

CSRF_TRUSTED_ORIGINS = env(
    'CSRF_TRUSTED_ORIGINS',
).split(',')

CORS_ALLOWED_ORIGINS = env(
    'CORS_ALLOWED_ORIGINS',
).split(',')




# Application definition

INSTALLED_APPS = [
    'apps.unfold_admin',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ============================
    # 3rd Party Apps
    # ============================
    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
    'django_celery_results',
    'django_celery_beat',


    # ==================
    # Manual apps
    # ==================
    'apps.user',
    'apps.core',
    'apps.subscription',
    'apps.payment',
    'apps.watchanalysis',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chronoverify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chronoverify.wsgi.application'


# ============================
# REST FRAMEWORK CONFIGURATION
# ============================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.JSONParser",
    ),
    # "DEFAULT_PERMISSION_CLASSES": (
    #     "rest_framework.permissions.IsAuthenticated",
    # )
}

# ============================
# CELERY CONFIGURATION
# ============================

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    default="redis://localhost:6379/0"
)
CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default="redis://localhost:6379/0"
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "UTC"

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

CELERY_RESULT_BACKEND = "django-db"

CELERY_BEAT_SCHEDULE = {
    'cleanup-task': {
        'task': 'celery.backend_cleanup',
        'schedule': crontab(hour=4, minute=0),
    },
    'grant-free-scans': {
        'task': 'apps.user.tasks.grant_free_scans_to_users_bulk',
        'schedule': crontab(hour=0, minute=0),  # Run daily at midnight
    },
    'downgrade-expired-subscriptions': {
        'task': 'apps.user.tasks.downgrade_expired_subscriptions',
        'schedule': crontab(hour=1, minute=0),  # Run daily at 1 AM
    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="noreply@chronoverify.com"
)

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")

FIREBASE_SERVICE_ACCOUNT_FILE = str(BASE_DIR / "firebase" / "serviceAccountKey.json")



#################################


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'user.User'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

OPENAI_API_KEY = env('OPENAI_API_KEY')
OPENAI_MODEL = env('OPENAI_MODEL')


# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apps.user.firebase': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.user.serializers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.payment.revenuecat_service': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.payment.webhook': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ============================================================================
# REVENUECAT CONFIGURATION
# ============================================================================
# Get these from your RevenueCat Project Settings
REVENUECAT_API_KEY = env(
    "REVENUECAT_API_KEY",
    default=""
)
REVENUECAT_SECRET_KEY = env(
    "REVENUECAT_SECRET_KEY",
    default=""
)

# RevenueCat webhook signature verification secret
# Used in webhook handler to validate incoming webhook requests


# ===========================
# Unfold Csonfiguration
# ===========================


UNFOLD = {
    "SITE_TITLE": "ChronoVerify Admin",
    "SITE_HEADER": "ChronoVerify",
    "SITE_SUBHEADER": "Admin Dashboard",
    # "SITE_LOGO": {
    #     "light": lambda request: static("admin/react.svg"),  # Path to your file
    #     "dark": lambda request: static("admin/react.svg"),   # Use same or different for dark mode
    # },
    "SITE_SYMBOL": "apartment",  # Use an icon name from Unfold's icon library
    # Update this path to include the 'apps' prefix
    "DASHBOARD_CALLBACK": "apps.unfold_admin.dashboard.dashboard_callback",
    "DASHBOARD_TEMPLATE": "admin/dashboard.html",
    
    # Also update any other callbacks or links (Environment, Sidebar, etc.)
    "ENVIRONMENT": "apps.unfold_admin.dashboard.environment_callback",
    
    "INDEX_VIEW": "apps.unfold_admin.views.CustomIndexView",
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            # --- ADDED THIS DASHBOARD SECTION ---
            {
                "title": "Navigation",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard", 
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            # ------------------------------------
            {
                "title": "Account",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "group", 
                        "link": reverse_lazy("admin:user_user_changelist"),
                    },
                ],
            },
            {
                "title": "Subscriptions",
                "separator": True,
                "items": [
                    {
                        "title": "Subscription Plans",
                        "icon": "loyalty",
                        "link": reverse_lazy("admin:subscription_subscriptionplan_changelist"),
                    },
                    {
                        "title": "Subscriptions",
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:subscription_subscription_changelist"),
                    },
                ],
            },
            {
                "title": "Payments",
                "separator": True,
                "items": [
                    {
                        "title": "In-App Purchases",
                        "icon": "payments",
                        "link": reverse_lazy("admin:payment_inapppurchase_changelist"),
                    },
                ],
            },
            {
                "title": "Watch Analysis",
                "separator": True,
                "items": [
                    {
                        "title": "Watch Analyses",
                        "icon": "watch",
                        "link": reverse_lazy("admin:watchanalysis_watchanalysis_changelist"),
                    },
                    {
                        "title": "Usage Logs",
                        "icon": "history",
                        "link": reverse_lazy("admin:watchanalysis_usagelog_changelist"),
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "primary": {
                "50": "255 247 237",
                "100": "255 237 213",
                "200": "254 215 170",
                "300": "253 186 116",
                "400": "251 146 60",
                "500": "249 115 22",   # Base Orange
                "600": "234 88 12",
                "700": "194 65 12",
                "800": "154 52 18",
                "900": "124 45 18",
                "950": "67 20 7",
            },
        },
}