# Generated by Django 6.0 on 2025-12-22 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('front_image', models.ImageField(upload_to='watches/front/%Y/%m/')),
                ('back_image', models.ImageField(upload_to='watches/back/%Y/%m/')),
                ('bracelet_image', models.ImageField(upload_to='watches/bracelet/%Y/%m/')),
                ('authenticity_level', models.CharField(blank=True, choices=[('original', 'Original'), ('similar', 'Similar to Original'), ('fake', 'Fake'), ('inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('brand_detected', models.CharField(blank=True, max_length=100)),
                ('model_detected', models.CharField(blank=True, max_length=100)),
                ('analysis_details', models.JSONField(blank=True, default=dict, help_text='Detailed AI analysis results including all metrics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch Analysis',
                'verbose_name_plural': 'Watch analyses',
                'db_table': 'watch_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('scan', 'Watch Scan'), ('subscription_purchased', 'Subscription Purchased'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('login', 'User Login')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchanalysis.watchanalysis')),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'db_table': 'usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='watchanalysis',
            index=models.Index(fields=['user', 'created_at'], name='watch_analy_user_id_1252f6_idx'),
        ),
        migrations.AddIndex(
            model_name='watchanalysis',
            index=models.Index(fields=['status'], name='watch_analy_status_22e2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='watchanalysis',
            index=models.Index(fields=['authenticity_level'], name='watch_analy_authent_bcc781_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['user', 'action_type', 'created_at'], name='usage_logs_user_id_6d0177_idx'),
        ),
    ]
