# Generated by Django 5.2.9 on 2025-12-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchanalysis',
            name='estimated_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='watchanalysis',
            name='estimated_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
