# Generated by Django 5.2.9 on 2025-12-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0002_watchanalysis_estimated_price_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchanalysis',
            old_name='estimated_price_max',
            new_name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='watchanalysis',
            name='estimated_price_min',
        ),
    ]
