# Generated by Django 5.2.9 on 2025-12-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0003_rename_estimated_price_max_watchanalysis_estimated_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchanalysis',
            name='estimated_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
