# Generated by Django 5.2.9 on 2026-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0004_alter_watchanalysis_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchanalysis',
            name='language',
            field=models.CharField(default='English', help_text='Language preference for the analysis report', max_length=20),
        ),
    ]
