# Generated by Django 5.2.9 on 2026-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0005_watchanalysis_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchanalysis',
            name='invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchanalysis',
            name='original_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchanalysis',
            name='original_brand_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
