# Generated by Django 5.2.9 on 2026-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanalysis', '0006_watchanalysis_invoice_watchanalysis_original_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchanalysis',
            name='analysis_report_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
