# Generated by Django 6.0 on 2025-12-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('pay_per_scan', 'Pay Per Scan'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], default='free', max_length=20),
        ),
    ]
