# Generated by Django 5.2.9 on 2026-01-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French')], default='en', max_length=10),
        ),
    ]
