# Generated by Django 5.2.9 on 2026-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French')], default='english', max_length=10),
        ),
    ]
