# Generated by Django 5.2.9 on 2026-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_language_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_and_conditions_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
