# Generated by Django 5.2.9 on 2026-01-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('user', '0005_user_language_preference'),
        ('watchanalysis', '0004_alter_watchanalysis_estimated_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIandCostMonitoringProxy',
            fields=[
            ],
            options={
                'verbose_name': 'AI & Cost Monitoring',
                'verbose_name_plural': 'AI & Cost Monitoring',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('watchanalysis.watchanalysis',),
        ),
        migrations.CreateModel(
            name='AnalysisMetricsProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Analysis Metrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('watchanalysis.watchanalysis',),
        ),
        migrations.CreateModel(
            name='GeographicCurrencyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Geographic & Currency Data',
                'verbose_name_plural': 'Geographic & Currency Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='ReportsMetricsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reports Metrics',
                'verbose_name_plural': 'Reports Metrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('watchanalysis.watchanalysis',),
        ),
        migrations.CreateModel(
            name='RevenueMetricsProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Revenue Metrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.inapppurchase',),
        ),
        migrations.CreateModel(
            name='RiskMonitoringProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Risk Monitoring & Alerts',
                'verbose_name_plural': 'Risk Monitoring & Alerts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='SystemOverviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'System Overview',
                'verbose_name_plural': 'System Overview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('watchanalysis.watchanalysis',),
        ),
        migrations.CreateModel(
            name='UserMetricsProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'User Metrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
