# Generated by Django 6.0 on 2025-12-22 23:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0004_subscriptionplan_apple_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('google', 'Google Play'), ('apple', 'Apple App Store')], max_length=10)),
                ('google_order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_purchase_token', models.TextField(blank=True, null=True)),
                ('google_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('apple_original_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_receipt_data', models.TextField(blank=True, null=True)),
                ('apple_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(help_text='Product ID from store', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(help_text='The subscription plan that was purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='subscription.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In App Purchase',
                'verbose_name_plural': 'In App Purchases',
                'db_table': 'in_app_purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='in_app_purc_user_id_5652f4_idx'), models.Index(fields=['platform', 'status'], name='in_app_purc_platfor_023b48_idx'), models.Index(fields=['google_order_id'], name='in_app_purc_google__a79c6b_idx'), models.Index(fields=['apple_transaction_id'], name='in_app_purc_apple_t_e85542_idx')],
            },
        ),
    ]
