# Generated by Django 5.2.9 on 2026-02-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inapppurchase',
            name='rc_customer_id',
            field=models.CharField(blank=True, help_text='RevenueCat customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inapppurchase',
            name='rc_entitlement_id',
            field=models.CharField(blank=True, help_text='RevenueCat entitlement identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inapppurchase',
            name='rc_transaction_id',
            field=models.CharField(blank=True, help_text='RevenueCat transaction ID', max_length=255, null=True, unique=True),
        ),
    ]
