# Generated by Django 5.2.9 on 2026-04-23 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_inapppurchase_rc_customer_id_and_more'),
        ('subscription', '0008_alter_subscriptionplan_apple_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inapppurchase',
            name='rc_customer_id',
            field=models.CharField(blank=True, help_text='RevenueCat customer ID (user email / app_user_id)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inapppurchase',
            index=models.Index(fields=['rc_transaction_id'], name='in_app_purc_rc_tran_e3298a_idx'),
        ),
        migrations.AddIndex(
            model_name='inapppurchase',
            index=models.Index(fields=['rc_customer_id'], name='in_app_purc_rc_cust_2251e4_idx'),
        ),
    ]
