# Generated by Django 6.0 on 2025-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('pay_per_scan', 'Pay Per Scan'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], max_length=20),
        ),
    ]
