# Generated by Django 6.0 on 2025-12-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, help_text='Product ID in App Store Connect', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, help_text='Product ID in Google Play Console', max_length=255, null=True),
        ),
    ]
