# Generated by Django 5.2.9 on 2025-12-27 19:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_apple_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['category', 'sort_order', 'price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='analysis_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('ultimate', 'Ultimate')], default='basic', help_text='Level of analysis detail', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='basic_authenticity_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_download_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('free', 'Free'), ('pay_per_scan', 'Pay Per Scan'), ('premium', 'Premium Subscription'), ('unlimited', 'Premium Unlimited')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='component_detail_level',
            field=models.IntegerField(default=0, help_text='0=None, 1=Scores only, 2=Scores+Brief, 3=Full details', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='fast_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_price_estimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pdf_includes_stamps',
            field=models.BooleanField(default=False, help_text='Include official authenticity stamps in PDF'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pdf_is_bilingual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_processing',
            field=models.BooleanField(default=False, help_text='Skip queue for faster processing'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_component_breakdown',
            field=models.BooleanField(default=False, help_text='Show individual component scores (Dial, Caseback, etc.)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_component_observations',
            field=models.BooleanField(default=False, help_text='Show detailed observations for each component'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_confidence_metrics',
            field=models.BooleanField(default=False, help_text='Show detailed confidence scores and statistics'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_expert_notes',
            field=models.BooleanField(default=False, help_text='Show AI expert commentary'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_watch_information',
            field=models.BooleanField(default=False, help_text='Show brand, model, serial number'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_analyses',
            field=models.BooleanField(default=False, help_text='No limit on number of analyses per month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration in days for subscriptions, 0 for one-time', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text="Display name (e.g., 'Standard Analysis')", max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='scans_included',
            field=models.IntegerField(default=0, help_text='Number of scans (0 = unlimited for subscriptions)'),
        ),
    ]
