# Generated by Django 5.2.9 on 2026-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text='Language for this plan', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('name', 'language', 'category')},
        ),
    ]
