# Generated by Django 5.2.9 on 2026-01-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriptionplan_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
