# Generated by Django 5.2.9 on 2026-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscriptionplan_apple_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
